### PR TITLE
Fix tests

### LINKED ISSUE #2: DockerFile: Do not write to HOME directory
I'm currently trying the `DockerFile` in the context of singularity where at build time no HOME directory is available. This makes e.g. the download of anaconda fail which is (unnecessarily) downloaded to `~`.

In general I'd suggest downloading all temporary files/github repos/... to `/tmp` which also makes the intention clear. Currently most temporary files are put into the root folder `/`

### LINKED ISSUE #3: DockerFile: Install ffmpeg via conda
Using `imageio.plugins.ffmpeg.download()` is deprecated and removed in recent versions of `imageio`. The suggested alternative is `conda install ffmpeg -c conda-forge`

Additionally using the non-conda install does not work correctly if no HOME exists (see #2)

See; https://github.com/imageio/imageio/blob/v2.3.0/imageio/plugins/ffmpeg.py#L124
and https://github.com/imageio/imageio/blob/v2.5.0/imageio/plugins/ffmpeg.py#L39

Edit: Due to an issue (https://github.com/conda-forge/ffmpeg-feedstock/issues/49) the required command is `conda install ffmpeg x264=20131218 -c conda-forge`

### LINKED ISSUE #4: Don't store temporary  files in working directory
In this line https://github.com/ahrnbom/strudl/blob/3f12c83ffc02d96ddb03775234879e39d3ff84e2/tracks_formats.py#L35 a temporary folder `tmp.txt` in the current working directory is (going to be) created.

Please use `/tmp` for that (or more generically the system temp dir)

This is potentially faster and removes a dependency from the current folder.

### LINKED ISSUE #5: GPU requirements?
I'm trying to run the tests and the first failure I get is 

`E tensorflow/stream_executor/cuda/cuda_driver.cc:806] failed to allocate 11.17G (11996954624 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory`

This looks like a lot of memory. Is this intended to be that much? How much GPU memory is required for "regular execution"?

### PR DESCRIPTION
**Pull request by Flamefire**
Running STRUDL tests on our cluster I found a couple issues which I fixed here so I get all green:

- Timeout for train test was to small -> Increased to 600s
- Don't use all GPU memory (fixes #5)
- Don't write to current directory (tmp.txt) as it might be read-only but write to archive directly which is even the better approach (fixes #4)
- Install ffmpeg via apt (future proof approach allowing to even ditch conda for smaller image sizes, fixes #3 )
- put temporary files into /tmp instead of home (fixes #2 )

### CODE REVIEW

**Comment by ahrnbom** [comment]
Regarding the use of /data or /code/data, we have decided to use an environment variable to set the path to the data folder, and change folder.py to read this variable. The variable would then be set when building the docker image. This is useful when running STRUDL outside of docker. This will be implemented by us sometime soon.

Also, when you're making singularity files, are you making them something like this? `singularity build strudl.img docker://ahrnbom/strudl` ? Because that works for us, despite using the home folder, because the home folder is only used when Docker builds the image (which usually happens up on Dockerhub). Your changes might still make sense for generality, though.

**Comment by Flamefire** [comment]
> Regarding the use of /data or /code/data, we have decided to use an environment variable to set the path to the data folder, and change folder.py to read this variable.

Wouldn't that be more suitable for a parameter in the startup? It could still be set by an environment variable but that is translated into a parameter for server.py. This will make it easier when starting the docker container (setting env vars IN the container is harder than passing parameters to the "binary"/script)   
However this fix applies to current code and I'd suggest to include it because as-of-current state there is a bug.

> Also, when you're making singularity files, are you making them something like this? singularity build strudl.img docker://ahrnbom/strudl ?

I was actually converting the DockerFile to a Singularity.def via `spython`. This avoids having to build a docker container and then a singularity image from that allowing for faster turn-arounds   

Speaking of that: Building a container is very slow due to the massive amount of packages installed. I'd suggest:
- Reevaluate use of every package (apt, conda, pip) whether it is really required (e.g. git, svn **and** mercury?)
- Use miniconda or drop conda for a system python package together with pip packages
- Install all packages in one go (for each package manager)
  - This avoids costly resolving of dependencies and uninstalling previously installed packages due to changed dependencies

**Comment by ahrnbom** [comment]
I don't think that feeding the data path to server.py would help much, then it would also have to be sent to every single possible child process that server.py starts, which would be a pain. folder.py exists for this very reason, so we will continue to use it, in some way. I don't think making an environmental value in a Docker image is particularly difficult.

I very much agree that, currently, the Docker image is very polluted and poorly constructed. We made it "as we went along", adding things when we needed them. A total rewrite would be suitable. Unfortunately, this is quite time consuming, so I'm not sure when I will be able to do it.

**Comment by Flamefire** [comment]
> I don't think that feeding the data path to server.py would help much, then it would also have to be sent to every single possible child process that server.py starts. Which would be a pain. folder.py exists for this very reason, so we will continue to use it, in some way. 

A quick outline:
- Add `click.option` to `server.py::main` to receive a path (can even include validation)
- Call a function in `folder.py` passing it that path and which sets up all other paths
- Done

In general: There often is some kind of global state, like a database. In pure Flask (which connexion is based on) you have `app.instance_path` and `app.config['Key']=value` for configuration. These can be set initially and are available to all endpoints. Not sure about connextion though, but the principle still applies.

> I don't think making an environmental value in a Docker image is particularly difficult.

Compare with a parameter:   
Current:   
`nvidia-docker run -p 80:80 -v $DATAPATH:/code/data/ --mount type=bind,src=/media,dst=/usb,bind-propagation=rslave --rm -ti ahrnbom/strudl:$TAG`   
New:   
`nvidia-docker run -p 80:80 -v $DATAPATH:/my/data/path --mount type=bind,src=/media,dst=/usb,bind-propagation=rslave --rm -ti ahrnbom/strudl:$TAG --data_path=/my/data/path`

Anyway it doesn't even matter for the docker case: You simply bind your desired folder to the default data location.

What you gain is:
- Scalability: Using many environment variables does not scale well, adding parameters does
- Self-Documentation: `click` can generate a `--help` for your `server.py`
- Validation: E.g. ensure that the data_path exists by using `click`

**Comment by ahrnbom** [comment]
I don't understand how that function in folder.py would work. server.py launches new instances of python in its child processes, so no function in folder.py could change its behaviour in child process (as far as I know, at least, unless you resort to e.g. modifying the folder.py file when it's running, which sounds horrible). That's where I think an environment variable would be useful. Maybe I'm missing something?

**Comment by Flamefire** [comment]
Which child process are you referring too? I just tested the following in `folder.py` called from `main` in `server.py`:

```
paths = {'data': 'foobar'}
def mkPath(p):
  global paths
  paths['data'] = p
```

And verified that the value set is available in functions defined in `server.py` like (index_page) etc.

See example in https://github.com/zalando/connexion/blob/master/examples/openapi3/sqlalchemy/app.py: A `db_session` instance is created and used in all requests

**Comment by ahrnbom** [comment]
When server.py runs jobs, it uses the JobManager class from jobman.py which in turn launches shell commands, typically running python with one of the other scripts. So a global variable set from server.py would not be visible from the child processes created by it.

**Comment by Flamefire** [comment]
Ah, I see. I'd still suggest to make it an actual parameter for the advantages described above. Passing it to the child process can then still happen via an environment variable: `os.environ['DATA_PATH']=data_path` combined with appropriate handling in the server and folder.py (and possibly JobManager)

Unrelated: During scanning the code I found that the `queue` from the `JobManager` is not thread-safe but accessed by at least 2 threads (Worker and Server, where the server could use multiple threads too) This should be checked for validity   
Also filepath manipulation could be greatly improved. Instead of `format`, `split('/')` etc. functions like `os.path.basename`, `os.path.join` or even better the full `pathlib.Path` should bed used. This would make the code much clearer.

**Comment by ahrnbom** [comment]
I think your approach for the data path makes sense. I will probably implement it like that, or something similar. I also think it would be good if folder.py has some logic, where if the environment variable isn't set, it looks for the folder in the two places it is most likely to be (`/data` and `./data`, in that order), making the parameter optional for our intended use cases. So if you mount the data folder to `/data`, that would be sufficient. 

As for the paths thing (splot and format), I absolutely agree with you. I was not aware of those APIs when coding most of STRUDL. That's on the to-do list.

**Comment by Flamefire** [comment]
From experience I'd suggest to NOT provide the fallbacks but simply fail hard (raise exception) if environment variable is not set and nothing is configured. `folder.py` could be simplified to a `folders` function which returns the object creating it if it did not exist and `setupFolders` which is called by `main`. The parameter to main can be optional though.   
This way forgotten settings are detected instead of silently using an unexpected folder.

Anyway, let's talk about this PR: Please review and feel free to add comments if there are any questions or change requests.

**Comment by ahrnbom** [comment]
I haven't had time to look through all the changes in this PR yet, but what I have looked at does look good. Unless I find anything problematic, I think I'll pull this in, and then make some of the changes we've discussed on top of that.

**Pull request merged**
